### ISSUE TITLE
Implement /fi for filtering

### ISSUE THREAD

**Issue by dbkaplun** [sindresorhus/tasklist#1]
https://technet.microsoft.com/en-us/library/bb491010.aspx

**Comment by sindresorhus** [comment]
I considered it, but why not just use JS for that? Using JS would be a lot more readable. I guess I just didn't see the benefit. But happy to be convinced otherwise.

**Comment by dbkaplun** [comment]
Well, it seems like certain columns can be filtered via CLI options that are not sent as output (like CPU usage). I also noticed a `/svc` option in that link "Lists all the service information for each process without truncation" but I don't have Windows to test on so I don't know how the output would differ.

**Comment by sindresorhus** [comment]
Yeah, I guess it's valid then. Though I don't personally need this, so PR welcome for now, and I'll eventually get to this.
