### ISSUE TITLE
Is it possible to get 'private working set' of memory ?

### ISSUE THREAD

**Issue by vaidyaanand** [sindresorhus/tasklist#15]
Hi there,
         This package is very nice and fast way to get the tasklist on windows. I have compared the response time of this and other, Thanks to your effort. I am getting applications list from the following code:
```
 tasklist({
      verbose: true
    })
    .then(apps => {
      apps = apps
        .filter(app => app.sessionName !== 'Services')
        .filter(app => /^(?!NT AUTHORITY).+\\/.test(app.username));
      console.log(apps);
      apps.forEach(function (singleApp, index) {
      console.log(singleApp.memUsage);
      });
      cps.get(function (err, processes) {
      });
    })
    .catch(console.error);
```
 `memUsage` which I am getting from above API is 'working set'(shared) memory details. is there any way to get 'private working set' in windows?

**Comment by MarkTiedemann** [comment]
Yes, in Windows, you can use [`Win32_PerfRawData_PerfProc_Process#PrivateBytes`](https://msdn.microsoft.com/en-us/library/aa394323(v=vs.85).aspx) to get the private WS.

In Powershell, you can retrieve this perf data with the [`Get-WmiObject`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-wmiobject?view=powershell-5.1) cmdlet and the corresponding formatted data class `Win32_PerfFormattedData_PerfProc_Process`:

```powershell
Get-WmiObject -Class Win32_PerfFormattedData_PerfProc_Process `
  | Where-Object { $_.name -eq $PID } `
  | # Process perf data
```

**Comment by vaidyaanand** [comment]
Is there any API or key in this package to access it? because I am not getting what code you mentioned. I am new to this

**Comment by MarkTiedemann** [comment]
No, there's no API for accessing this information in this module. This module is just a wrapper around `tasklist.exe` - nothing more, nothing less.

I mentioned that you can access the information that you need using Powershell since Powershell is a shell that is installed on Windows by default (press your Windows key, type `powershell` and press Enter to open it) so it's kinda easy to get started with it.

If absolutely necessary, you could write a Powershell script to gather and print that information, and then use the Node [`child_process`](https://nodejs.org/api/child_process.html) module to execute that Powershell script (for example, `powershell.exe -NoLogo -NonInteractive -File Private-WS.ps1 123`) and retrieve the information that you want. Since you are new to this, I wouldn't recommend this, however.

**Comment by vaidyaanand** [comment]
Thanks, @MarkTiedemann, your information is really helpful. I will try to implement this. If I get success in the implementation I will put the code for reference, Just in case if anybody needs in the future.

**Comment by vaidyaanand** [comment]
For those, we are new to this:
you can use PowerShell ISE to create script (.ps1) file
see [Win32_PerfRawData_PerfProc_Process](https://msdn.microsoft.com/en-us/library/aa394323(v=vs.85).aspx)
add following : (You can use filter, iterate objectArray, inside it to get desired result)
 `Get-WmiObject -Class Win32_PerfRawData_PerfProc_Process  -Property IDProcess,CreatingProcessID,PercentProcessorTime,TimeStamp_Sys100NS,ElapsedTime`

In child_process add permission  and done
```
var spawn = require("child_process").spawn,
  child;
var enable = spawn("powershell.exe", ["-Command", "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"]);
enable.stderr.on("data", function (data) {
  //Go to Shared Memory
  console.log("enable Error Occured");
});

enable.on("exit", function () {
  try{
    child = spawn("powershell.exe", [path.join(__dirname, '/myFile.ps1')]);

  var overAllData = '';
  var count = 0;
  child.stdout.on("data", function (data) {
    console.log(data);
   // Add buffer to iterate data
  });

  child.stderr.on("data", function (data) {
    //Go to Shared Memory
    console.log("Powershell Errors Occured");
  });

  child.on("exit", function () {
      console.log("process exit");
    
  });
  child.stdin.end(); //end input
  }
  catch(err){
  //Go to Shared Memory
  console.log("error occured");
  }
  
});
enable.stdin.end(); //end input
```
Enjoy !

**Comment by MarkTiedemann** [comment]
@vaidyaanand Glad you made it!

I just thought about something else that might help you: [NodeRT](https://github.com/NodeRT/NodeRT).

NodeRT allows you to consume WinRT modules from Node.

For example, you can get extensive process diagnostics this way with pure JavaScript:

```javascript
// https://docs.microsoft.com/en-us/uwp/api/windows.system.diagnostics
const { ProcessDiagnosticInfo } = require('@nodert-win10-cu/windows.system.diagnostics')

let pid = 0

// https://docs.microsoft.com/en-us/uwp/api/windows.system.diagnostics.processdiagnosticinfo.trygetforprocessid#Windows_System_Diagnostics_ProcessDiagnosticInfo_TryGetForProcessId_System_UInt32_
let processDiagnosticInfo = ProcessDiagnosticInfo.tryGetForProcessId(pid)

// https://docs.microsoft.com/en-us/uwp/api/windows.system.diagnostics.processdiagnosticinfo.memoryusage#Windows_System_Diagnostics_ProcessDiagnosticInfo_MemoryUsage
let memoryUsage = processDiagnosticInfo.memoryUsage

// https://docs.microsoft.com/en-us/uwp/api/windows.system.diagnostics.processmemoryusage.getreport#Windows_System_Diagnostics_ProcessMemoryUsage_GetReport
let processMemoryUsageReport = memoryUsage.getReport()

// https://docs.microsoft.com/en-us/uwp/api/windows.system.diagnostics.processmemoryusagereport
let result = {
  nonPagedPoolSizeInBytes: processMemoryUsageReport.nonPagedPoolSizeInBytes,
  pageFaultCount: processMemoryUsageReport.pageFaultCount,
  pageFileSizeInBytes: processMemoryUsageReport.pageFileSizeInBytes,
  pagedPoolSizeInBytes: processMemoryUsageReport.pagedPoolSizeInBytes,
  peakNonPagedPoolSizeInBytes: processMemoryUsageReport.peakNonPagedPoolSizeInBytes,
  peakPageFileSizeInBytes: processMemoryUsageReport.peakPageFileSizeInBytes,
  peakPagedPoolSizeInBytes: processMemoryUsageReport.peakPagedPoolSizeInBytes,
  peakVirtualMemorySizeInBytes: processMemoryUsageReport.peakVirtualMemorySizeInBytes,
  peakWorkingSetSizeInBytes: processMemoryUsageReport.peakWorkingSetSizeInBytes,
  privatePageCount: processMemoryUsageReport.privatePageCount,
  virtualMemorySizeInBytes: processMemoryUsageReport.virtualMemorySizeInBytes,
  workingSetSizeInBytes: processMemoryUsageReport.workingSetSizeInBytes
}

console.log(result)
/* { nonPagedPoolSizeInBytes: 99440,
     pageFaultCount: 8612689,
     pageFileSizeInBytes: 223186944,
     pagedPoolSizeInBytes: 895328,
     peakNonPagedPoolSizeInBytes: 558456,
     peakPageFileSizeInBytes: 398995456,
     peakPagedPoolSizeInBytes: 1036720,
     peakVirtualMemorySizeInBytes: 2201167859712,
     peakWorkingSetSizeInBytes: 452255744,
     privatePageCount: 223186944,
     virtualMemorySizeInBytes: 2201037660160,
     workingSetSizeInBytes: 253259776 } */
```

**Comment by MarkTiedemann** [comment]
@vaidyaanand Another alternative: [`win-proc-info`](https://github.com/MarkTiedemann/node-win-proc-info).

```js
const procInfo = require('win-proc-info')

console.log(procInfo(process.pid))
/* { pageFaultCount: 6178,
     pagefileUsage: 10211328,
     peakPagefileUsage: 10690560,
     peakWorkingSetSize: 21942272,
     privateUsage: 10211328,
     quotaNonPagedPoolUsage: 12960,
     quotaPagedPoolUsage: 164960,
     quotaPeakNonPagedPoolUsage: 12960,
     quotaPeakPagedPoolUsage: 164960,
     workingSetSize: 21942272 } */
```

**Comment by vaidyaanand** [comment]
@MarkTiedemann
Thank you. It is good alternative.
Please accept delay in my response as I am outing. Let me check this on Monday and let you know.

**Comment by MarkTiedemann** [comment]
@vaidyaanand No worries, I'm glad I can help.

By the way, here's another alternative for getting access to Windows UWP APIs: [`uwp`](https://github.com/Microsoft/node-uwp). This module only runs on [Node ChakraCore](https://github.com/nodejs/node-chakracore), though.

**Comment by vaidyaanand** [comment]
@MarkTiedemann Both the alternatives are great. I am using ChakraCore and it is working fine on my system.
Thank you

**Comment by vaidyaanand** [comment]
@MarkTiedemann Is there any way to differentiate 'system' process or any way to identify 'pid' belongs to system process?

**Comment by MarkTiedemann** [comment]
Depends on what "system process" means to you. Can you define that more precisely?

I suggest you run `tasklist.exe /v` and check the `User Name` column. User names starting with `NT AUTHORITY` might be what you are looking for:

```
tasklist.exe /fi "username eq NT AUTHORITY\*"
```

In Node, you can filter using the [`filter`](https://github.com/sindresorhus/tasklist#filter) option (see [`test.js`](https://github.com/sindresorhus/tasklist/blob/master/test.js#L44) for an example).

**Comment by vaidyaanand** [comment]
@MarkTiedemann System process means. The process which system is using, i.e. processes which user has not started. like process from the system32 path. 
In  Win32_PerfRawData_PerfProc_Process#PrivateBytes I have checked I am getting working set only not private working set. I am looking for alternatives as you have specified above.

**Comment by vaidyaanand** [comment]
@MarkTiedemann I am getting error while using [node-win-proc-info](https://github.com/MarkTiedemann/node-win-proc-info) Please check:
![error](https://user-images.githubusercontent.com/22315535/42569211-66976b4a-852d-11e8-8e32-41aa080b7762.png)

**Comment by vaidyaanand** [comment]
@MarkTiedemann I am getting error while executing [node-win-proc-info](https://github.com/MarkTiedemann/node-win-proc-info) Please check:
![error](https://user-images.githubusercontent.com/22315535/42569347-dac70106-852d-11e8-91a6-3032aba3ae8f.png)

**Comment by vaidyaanand** [comment]
Following is the code I needed, But how can I execute for all process including all PID for current userName, I am unable to make it till now.
`(Get-Counter "\Process(code)\Working Set - Private" -ErrorAction SilentlyContinue).CounterSamples`
Where: code stands for 'Visual studio code, I need it for all application I make it *
`(Get-Counter "\Process(*)\Working Set - Private" -ErrorAction SilentlyContinue).CounterSamples`
But it is not providing me PID. How can I get this? Or is there any other way we can pass PID in above code?
We can pass indexes to it, but indexes changes with time.
`(Get-Counter "\Process(code#1)\Working Set - Private" -ErrorAction SilentlyContinue).CounterSamples`
We need something which is dependent on PID

**Comment by MarkTiedemann** [comment]
@vaidyaanand Moved the `node-win-proc-info` issue to [https://github.com/MarkTiedemann/node-win-proc-info/issues/1](https://github.com/MarkTiedemann/node-win-proc-info/issues/1).

And I'm sorry, but I can't check your `Get-Counter` code since performance counters are currently not available on my Windows system.
