### ISSUE TITLE
I am trying to build it with browserify

### ISSUE THREAD

**Issue by huzoorbux** [sindresorhus/tasklist#27]
I am build this package with browserify  now i am getting below error

```
VM165 bundle.js:7184 Uncaught TypeError: promisify is not a function
    at Object.<anonymous> (VM165 bundle.js:7184)
    at Object.43._process (VM165 bundle.js:7247)
    at o (VM165 bundle.js:1)
    at VM165 bundle.js:1
    at Object.34.tasklist (VM165 bundle.js:6505)
    at o (VM165 bundle.js:1)
    at r (VM165 bundle.js:1)
    at VM165 bundle.js:1
```

how to fix it please help.

**Comment by sindresorhus** [comment]
This is not the place to ask for Browserify support.

**Comment by huzoorbux** [comment]
Ok thanks. I am using your tasklist module that's why i thaut you can help me with that sorry.

**Comment by MarkTiedemann** [comment]
@huzoorbux Also note that you should not use `tasklist` in the browser. This module executes `tasklist.exe` when run on a Windows machine. It simply does not work in the browser.

**Comment by huzoorbux** [comment]
Thanks, dear foud another module which solved my problem :)
