### ISSUE TITLE
Verbose setting isn't working

### ISSUE THREAD

**Issue by vaxinc** [sindresorhus/tasklist#30]
This work
`(async () => {
    console.log(await tasklist());
})();`
This doesn't
`(async () => {
    console.log(await tasklist({verbose: true}));
})();`

No errors, just nothing. It seems as if the async function assigned to this task, completely stop working or is just running in a loop that cant be resolved. Is there something im missing, like some setting tweaking i need to do beforehand, or something completely different?

**Comment by MarkTiedemann** [comment]
@vaxinc As written in the README.md, `verbose` is slow.

> Warning: Using the verbose option may have a considerable performance impact (See: #6).

On my machine, for example, it taskes almost 6 seconds to print the verbose tasklist.

```js
const tasklist = require("tasklist");

(async () => {
  console.time();
  console.log(await tasklist({ verbose: true }));
  console.timeEnd();
})();
```

```
default: 5.833s
```

**Comment by vaxinc** [comment]
> @vaxinc As written in the README.md, `verbose` is slow.
> 
> > Warning: Using the verbose option may have a considerable performance impact (See: #6).
> 
> On my machine, for example, it taskes almost 6 seconds to print the verbose tasklist.
> 
> ```js
> const tasklist = require("tasklist");
> 
> (async () => {
>   console.time();
>   console.log(await tasklist({ verbose: true }));
>   console.timeEnd();
> })();
> ```
> 
> ```
> default: 5.833s
> ```

i see, apologize for the inconvience. Apparently i either have a slow machine or too many tasks open
`default: 69839.55395507812 ms`

Is there a way to optimize this? Like only look for tasks with a certain imagename?

**Comment by vaxinc** [comment]
`(async () => {
  console.log(console.time());
  var taskArr;
  taskArr = await tasklist();
  var SpotifyPid;
  for(var i = 0; i < taskArr.length; i++){
    if(taskArr[i].imageName == "Spotify.exe"){
        SpotifyPid = taskArr[i].pid;
    }
  }
  var SpotifyTask = await tasklist({verbose: true, pid: SpotifyPid}) //This doesn't work btw
  console.log(SpotifyTask.windowTitle);
  console.log(console.timeEnd());

})();`

Something like this perhaps, dont know why the code markup wont work

**Comment by MarkTiedemann** [comment]
> Apparently i either have a slow machine or too many tasks open `default: 69839.55395507812 ms`

@vaxinc `tasklist.exe` is quite slow in general. (Hence, I created [`fastlist.exe`](https://github.com/marktiedemann/fastlist). Alternatively, `wmic process` may be faster on your machine, too (e.g. `wmic.exe process get name,processid,parentprocessid`).).

What's your use-case? Maybe I'm able to help if I know your requirements.

**Comment by vaxinc** [comment]
> > Apparently i either have a slow machine or too many tasks open `default: 69839.55395507812 ms`
> 
> @vaxinc `tasklist.exe` is quite slow in general. (Hence, I created [`fastlist.exe`](https://github.com/marktiedemann/fastlist). Alternatively, `wmic process` may be faster on your machine, too (e.g. `wmic.exe process get name,processid,parentprocessid`).).
> 
> What's your use-case? Maybe I'm able to help if I know your requirements.

An electronjs application that uses genius.com's api to retrieve lyrics for the current playing spotify song. I've developed this exact same app through pygame, so i know the procedure to it. The thing about spotify is that whenever you are playing a song, the windowTitle will change to the song name, so therefore the most efficient way to get the current playing song on spotify would be to look for the spotify.exe task and retrieve it's title. I'll look into fastlist though, thanks

**Comment by MarkTiedemann** [comment]
How about? 

```
powershell -c "get-process -name spotify | where { $_.mainwindowtitle } | select -expand mainwindowtitle"
```

e.g.

```js
const child_process = require("child_process");

function current_spotify_song() {
    return new Promise(resolve => {
        child_process.execFile("powershell.exe", [ "-c", "get-process -name spotify | where { $_.mainwindowtitle } | select -expand mainwindowtitle" ], (err, stderr) => {
            if (err) {
                // No permission to execute powershell
                return resolve(null);
            }
            let song = stderr.trim();
            if (!song.includes(" - ")) {
                // Spotify is open but there's no song playing
                return resolve(null);
            }
            resolve(song);
        });
    });
}

(async () => {
    console.log(await current_spotify_song());
})();
```

**Comment by MarkTiedemann** [comment]
Actually, on second thought, `tasklist` should work fine, too. You will need a `filter`, though.

```js
const tasklist = require("tasklist");

(async () => {
    let spotify_tasks = await tasklist({ verbose: true, filter: ["imagename eq spotify.exe"] });
    console.log(spotify_tasks);
})();
```

Does this have acceptable performance on your machine?

**Comment by vaxinc** [comment]
> Actually, on second thought, `tasklist` should work fine, too. You will need a `filter`, though.
> 
> ```js
> const tasklist = require("tasklist");
> 
> (async () => {
>     let spotify_tasks = await tasklist({ verbose: true, filter: ["imagename eq spotify.exe"] });
>     console.log(spotify_tasks);
> })();
> ```
> 
> Does this have acceptable performance on your machine?

YES! very much, under 500ms! Thank you man

**Comment by MarkTiedemann** [comment]
Glad this worked for you. :)
