### ISSUE TITLE
Syntax help

### ISSUE THREAD

**Issue by rfossella** [sindresorhus/tasklist#5]
Hi. Trying to use module to view tasklist from network computer but it is always displaying localhost processes.

```
tasklist(['/s "10.40.51.132"', '/u "mydomain\rfossella"', '/p "xxxyyy1123"' ]).then(function(data){
    console.log(data);
});
```

Is this syntax correct?

Thanks.

**Comment by sindresorhus** [comment]
No, you don't need to use the convoluted syntax. This module handles that for you. Just use the documented options → https://github.com/sindresorhus/tasklist#options ;)

**Comment by rfossella** [comment]
Hi.  Thanks for prompt response.  I did look at options but I always seem to get same "local" results.
e.g. each of these return identical results -i.e. no results from a remote computer

```
taskList({system:"10.40.51.132", user: "mydomain\rfossella", password:"xxxyyy1123"})...
taskList({system:"localhost"})...
taskList({})...
taskList()...
```

Based on options in doc it looks like first one should work.  It does work w/similar Windows options from a command line.

Thanks for your help.

**Comment by sindresorhus** [comment]
It does pretty much what you did internally https://github.com/sindresorhus/tasklist/blob/7cd94020412606133a472754f1244e7e77051155/index.js#L18, so I don't really know.

**Comment by rfossella** [comment]
Should is just be a positional array instead of a json object?
instead of 
 `taskList({system:"10.40.51.132", user: "mydomain\rfossella", password:"xxxxxx".....`
Should I use
`taskList(["10.40.51.132",  "mydomain\rfossella",   "xxxxxx"])`

**Comment by sindresorhus** [comment]
No, should be an object. I've done some docs improvements: https://github.com/sindresorhus/tasklist/commit/89c46258b634f4f941321cc1f91953ed2fb674ea

`"mydomain\rfossella"` should be `"mydomain\\rfossella"`, as backslashes must be escaped in strings.
