### ISSUE TITLE
Make /v flag optional

### ISSUE THREAD

**Issue by MarkTiedemann** [sindresorhus/tasklist#6]
`tasklist` seems to be round about 1 second slower when used with the verbose flag. Therefore, I propose making the `/v` flag optional.

______________

Using `timeit` from the [Windows Server 2003 Resource Kit Tools](https://www.microsoft.com/en-us/download/details.aspx?id=17657), I got the following outputs:

**`timeit tasklist`**:
```
Version Number:   Windows NT 6.2 (Build 9200)
Exit Time:        5:05 pm, Friday, March 3 2017
Elapsed Time:     0:00:00.114
Process Time:     0:00:00.015
System Calls:     56499
Context Switches: 23459
Page Faults:      6867
Bytes Read:       1708
Bytes Written:    117698
Bytes Other:      1061894
```

**`timeit tasklist /v`**:
```
Version Number:   Windows NT 6.2 (Build 9200)
Exit Time:        5:05 pm, Friday, March 3 2017
Elapsed Time:     0:00:01.359
Process Time:     0:00:00.062
System Calls:     244191
Context Switches: 65230
Page Faults:      43840
Bytes Read:       19524
Bytes Written:    648250
Bytes Other:      6542373
```

______________

Hope I'm gonna be able to submit a PR soon. :)

______________

EDIT: Just noticed there's already a closed issue regarding `tasklist` being slow: [https://github.com/sindresorhus/tasklist/issues/4](https://github.com/sindresorhus/tasklist/issues/4). It was closed as a `wontfix`. Making the `/v` flag optional, however, would be that missing fix.

______________

Another question in this regard would be: Should the `verbose` option be `true` or `false` by default? I'm leaning towards `false` considering the performance impact.

**Comment by sindresorhus** [comment]
What is the difference between verbose and non-verbose output?

**Comment by MarkTiedemann** [comment]
Normal output is:

-  `imageName`
- `pid`
- `sessionName`
- `sessionNumber`
- `memUsage`

Verbose output is (normal output plus):

- `status`
- `username`
- `cpuTime`
- `windowTitle`

Making the `/v` flag optional would be a breaking change, of course.

PS: Just writing a PR. :)

PPS: Love your work.

**Comment by MarkTiedemann** [comment]
Another thought: How about adding a stream or even emitter interface? This would be nice for running the verbose option on slow systems, especially if you're not interested in all tasks anyway.

**Comment by sindresorhus** [comment]
> How about adding a stream or even emitter interface?

Does `tasklist.exe` actually stream the output though?

**Comment by MarkTiedemann** [comment]
Yeah, `tasklist.exe` outputs in chunks.

For a streaming implementation, I'm thinking about something along the lines of this ...

```js
const spawn = require('child_process').spawn
const Transform = require('stream').Transform
const csv = require('csv')

module.exports = () => 
  spawn('tasklist.exe', ['/fo', 'csv'])
  .stdout
  .pipe(csv.parse({
    columns: [ 'imageName', 'pid', 'sessionName', 'sessionNumber', 'memUsage' ],
    from: 2 // skip header record
  }))
  .pipe(new Transform({
    objectMode: true,
    transform(task, encoding, callback) {
      callback(null, Object.assign(task, {
        pid: Number(task.pid),
        sessionNumber: Number(task.sessionNumber),
        memUsage: 1024 * Number(task.memUsage.replace(/[^\d]/g, ''))
      }))
    }
  }))
```

... which could be used like this ...

```js
const tasklist = require('tasklist')

tasklist()
  .on('data', console.log)
  /* => { imageName: 'tasklist.exe',
          pid: 9620,
          sessionName: 'Console',
          sessionNumber: 3,
          memUsage: 864420 } */
```

Should this be part of this module, though? Or would it be better to put it in a new one, for example, `tasklist-stream`?

**Comment by MarkTiedemann** [comment]
If anyone reading this issue is interested in a streaming interface, check out [`tasklist-stream`](https://github.com/MarkTiedemann/tasklist-stream). :)
